language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=origin/master

before_script:
    - curl -S http://getcomposer.org/installer | php
    - php composer.phar install

notifications:
  email:
    - attila.bukor@gmail.com
